### ISSUE TITLE
Community translations

### ISSUE THREAD

**Issue by r-tw0** [flauschtrud/broccoli#184]
What's the outlook on community translations, since Broccoli is now open source? I'd love to try to translate the app into Polish.

**Comment by flauschtrud** [comment]
Yes, that would be very much appreciated!

I just set up a project on crowdin, you should be able to join it via: https://crowdin.com/project/broccoli/invite?h=20e3ad82aeaed6d129ae18016bdf89191753803

I'm using this platform for the first time so please tell me if you encounter any problems using it, especially regarding access and roles.

**Comment by flauschtrud** [comment]
@r-tw0 Thanks already for all your help!

I just thought in case you wanted to test something: Crowdin pushes to the [l10n_master](https://github.com/flauschtrud/broccoli/tree/l10n_master) branch and you can fetch debug APKs here: https://github.com/flauschtrud/broccoli/actions/workflows/build.yml

**Comment by r-tw0** [comment]
@flauschtrud All done! I'll make sure to test it.

**Comment by r-tw0** [comment]
The app looks great! One more thing - is there going to be an option for the Polish language in the seasonal calendar? I imagine that's what the different terms for ingredients that I translated are for.

**Comment by flauschtrud** [comment]
> The app looks great! One more thing - is there going to be an option for the Polish language in the seasonal calendar? I imagine that's what the different terms for ingredients that I translated are for.

Yes! I'm going to add it to the seasonal calendar options.

It would also be interesting to hear an opinion about how well the seasonal calendar is suited to the Polish climate. The data is based on Germany where I did my research, but even northern and southern Germany are a little different ;)

**Comment by flauschtrud** [comment]
I just published a new release to the Play Store alpha track and if everything's fine I will trigger the new release for f-droid :)
