### ISSUE TITLE
Broccoli can't scrape based.cooking recipies

### ISSUE THREAD

**Issue by hhartzer** [flauschtrud/broccoli#203]
[based.cooking](https://github.com/LukeSmithxyz/based.cooking) is awesome! Unfortunately, Broccoli can't seem to scrape it.

I'm not sure if this is a metadata issue or what it would take to add support, so I am opening this issue on both ends.

Issue on based.cooking: https://github.com/LukeSmithxyz/based.cooking/issues/954

**Comment by flauschtrud** [comment]
I just had a look and yes, it's a metadata issue. Broccoli is looking for metadata in [JSON-LD format](https://json-ld.org/), but this site is extremely sparse (I assume intentionally) and does not provide any JSON-LD metadata.
Most websites and blogs use plugins that generate this kind of data, but this site seems to just collect the recipes as MD files without any additional structure.

**Comment by hhartzer** [comment]
Thank you! I will look into that.
