### ISSUE TITLE
Search Bar Bug: Quotation Marks

### ISSUE THREAD

**Issue by lo-vil** [flauschtrud/broccoli#213]
## Description

Typing " (quotation mark) in the search causes the app to crash, even though quotation marks can be added to recipe titles and descriptions.

## How to reproduce:
1. Launch Brocoli App
2. Click search icon
3. Type quotation mark (")

## Actual Behaviour
App Crashes

![Screenshot 2024-04-06 at 5 19 31 PM](https://github.com/SOEN345-WINTER2024/discussion/assets/94203138/ef5b83fc-dfab-4835-9db6-57038eb1a16f)

## Expected Behaviour
Simply put app should not crash. More specifically, if a recipe contains a quotation mark in its title, description, or url, then it should be queried and displayed in the recipe list. (Similar to if I type Chicken and the recipe Chicken Pasta recipe is displayed)

![Screenshot 2024-04-06 at 5 31 04 PM](https://github.com/SOEN345-WINTER2024/discussion/assets/94203138/ececba22-48d5-4d91-a341-cb1209269f76)

**Device Model:** Pixel 3a API 34
**Android Version:** Android 14.0
**App version:** v1.2.8-fdroid

## Duplicate Check
The issue has never been reported before.

**Comment by flauschtrud** [comment]
Thanks for reporting, this will be fixed for the next release!

Please note that the app uses SQLite's full-text search: https://sqlite.org/fts3.html
This means that almost all special characters (including quotes) are not indexed. The only exception is the # character which is important if you use hashtags in your recipes.
