### ISSUE TITLE
[Feature request] I would like to be able to run the app on desktop, is that possible?

### ISSUE THREAD

**Issue by C0smin** [flauschtrud/broccoli#220]
Hi, 

Would it be possible to have a desktop versio of this app?

Thanks

**Comment by flauschtrud** [comment]
There's no plan for a desktop app, but you might be able to run the android app on your PC: https://www.pcmag.com/how-to/3-free-ways-to-run-android-apps-on-your-pc (I have no personal experience with these apps and services)
